### ISSUE TITLE
ImportError: DLL load failed while importing libPyPointCloud3D: The specified module could not be found. 

### ISSUE THREAD

**Issue by abdulhafidz6** [UCLM-PAFyC/qLidar#1]
Dear Professor David, 

Thank you for this great plugin. Now we can open and edit LiDAR data natively in QGIS as alternative from LASTOOLS. However, when I try to activate the plugin, there is an error pop up. Is there another python module to install first? I try this plugin both in QGIS 3.16 and 3.22. Thank you in advance.
Hafidz

Couldn't load plugin 'qLidar' due to an error when calling its classFactory() method 

ImportError: DLL load failed while importing libPyPointCloud3D: The specified module could not be found. 
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/hp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qLidar\__init__.py", line 35, in classFactory
    from .qLidar import qLidar
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/hp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qLidar\qLidar.py", line 36, in 
    from libCpp.libPyPointCloud3D import IPyPC3DProject
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: DLL load failed while importing libPyPointCloud3D: The specified module could not be found.

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.16.12-Hannover Hannover, be6cb030 

Python Path:
C:\Users/hp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LAStools
C:\Users/hp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\fractaliadj
C:/OSGeo4W/apps/qgis-ltr/./python
C:/Users/hp/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/hp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGeo4W/apps/qgis-ltr/./python/plugins
C:\Program Files\Hexagon\ERDAS IMAGINE 2015\usr\lib\Win32Release\python
C:\OSGeo4W\bin\python39.zip
C:\OSGeo4W\apps\Python39\DLLs
C:\OSGeo4W\apps\Python39\lib
C:\OSGeo4W\bin
C:\Users\hp\AppData\Roaming\Python\Python39\site-packages
C:\OSGeo4W\apps\Python39
C:\OSGeo4W\apps\Python39\lib\site-packages
C:\OSGeo4W\apps\Python39\lib\site-packages\win32
C:\OSGeo4W\apps\Python39\lib\site-packages\win32\lib
C:\OSGeo4W\apps\Python39\lib\site-packages\Pythonwin
C:/Users/hp/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\hp\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
C:\Users\hp\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qLidar
C:\Users\hp\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qLidar\libCpp
C:\Users\hp\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\inasafe\safe_extras\parameters
C:\Users\hp\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
C:\Users\hp\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\inasafe\safe_extras
C:\Users\hp\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qLidar
C:\Users\hp\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qLidar\libCpp

**Comment by hamiltoncj** [comment]
I get the same error.

**Comment by andislazdins** [comment]
The same issue, Ubuntu 64 bit 20.04

**Comment by kleja** [comment]
Same issue, Manjaro KDE Plasma 5.22.5, QGIS 3.20.

**Comment by kleja** [comment]
> Same issue, Manjaro KDE Plasma 5.22.5, QGIS 3.20.

Quick note - this not working under Linux (all distros) might be due to libPyPointCloud3D being a .pyd... So, might be possible given a Windows python environment, but really would be nice to have a libPyPointCloud3D.so file ;)

**Comment by sferic** [comment]
The same issue under Windows10. Maybe the library is a private module by the developers?

**Comment by DavidHernandezLopez** [comment]
Sorry for the inconveniences
This plugin works for no MSI installers
Tested versions: 3.4 - 3.16 (not msi installers)
This plugin uses dlls in C++ linked to dependences previous to new MSI installers

**Comment by DavidHernandezLopez** [comment]
Please, send me any issue by email: david.hernandez@uclm.es

**Comment by abdulhafidz6** [comment]
Hi, thanks for your reply
I am using QGIS with Network Installer. It seems that the only current issue is the libPyPointCloud3D module is not available

**Comment by DavidHernandezLopez** [comment]
This plugis is compiled using c++ libraries. Please, try to use a standallone installer 3.16.x 64bits downloaded from the official repository https://qgis.org/downloads/, such as QGIS-OSGeo4W-3.16.7-1-Setup-x86_64.exe
